---
- hosts: localhost
  become: yes
  tasks:
    - name: Install Screen Terminator
      apt:
        name: screen
        update_cache: yes
        state: present
    - name: Install Network Tools
      apt:
        name: net-tools
        state: present
    - name: Install Wireless Tools
      apt:
        name: wireless-tools
        state: present
    - name: Install Network Manager
      apt:
        name: network-manager
        state: present
    - name: Install Pavucontrol
      apt:
        name: pavucontrol
        state: present
    - name: Install Rofi
      apt:
        name: rofi
        state: present
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars/nodejs_vars.yml
    - vars/terraform_vars.yml
    - vars/golang_vars.yml
    - vars/docker_vars.yml
    - vars/vscode_vars.yml
    - vars/pip_vars.yml
    - vars/helm.yml
  roles:
    - geerlingguy.nodejs
    - migibert.terraform
    - fubarhouse.golang
    - geerlingguy.docker
    - gantsign.visual-studio-code
    - geerlingguy.pip
    - geerlingguy.java
    - nephelaiio.rxvt-unicode
    - pixelart.chrome
