---
- hosts: localhost
  tasks:
    - name: Install Screen Terminator
      apt:
        name: screen
        state: present
  vars_files:
    - vars/nodejs_vars.yml
    - vars/terraform_vars.yml
    - vars/golang_vars.yml  
  roles:
    - geerlingguy.nodejs
    - migibert.terraform
    - fubarhouse.golang  
