---
- hosts: localhost
  become: yes
  tasks:
    - name: Import tasks to install utils
      import_tasks: tasks/install-utils.yml
    - name: Import tasks to install Azure CLI
      import_tasks: tasks/install-azure-cli.yml
    - name: Import tasks to install Dotnet Core 3.1
      import_tasks: tasks/install-dotnet-core.yml
    - name: Import tasks to install Obs
      import_tasks: tasks/install-obs.yml
    - name: Import tasks to install Slack
      import_tasks: tasks/install-slack.yml
    - name: Import tasks to install Azure Functions Cli
      import_tasks: tasks/install-az-func-cli.yml
  vars:
    ansible_python_interpreter: /usr/bin/python3
  vars_files:
    - vars/nodejs_vars.yml
    - vars/terraform_vars.yml
    - vars/golang_vars.yml
    - vars/docker_vars.yml
    - vars/vscode_vars.yml
    - vars/pip_vars.yml
    - vars/helm.yml
  roles:
    - gantsign.helm
    - geerlingguy.nodejs
    - migibert.terraform
    - fubarhouse.golang
    - geerlingguy.docker
    - gantsign.visual-studio-code
    - geerlingguy.pip
    - geerlingguy.java
    - pixelart.chrome
