- src: geerlingguy.nodejs
- src: migibert.terraform
- src: fubarhouse.golang
- src: geerlingguy.docker
- src: gantsign.visual-studio-code
- src: geerlingguy.pip
- src: geerlingguy.helm
- src: geerlingguy.git
- src: geerlingguy.java
- src: alzadude.firefox
- src: pixelart.chrome
