- name: Install PreReqs for Azure CLI
  apt:
    name: [ ca-certificates, curl, apt-transport-https, lsb-release, gnupg ]
    state: present
- name: Download and Install Microsoft Signing Key
  shell: curl -sL https://packages.microsoft.com/keys/microsoft.asc |
    gpg --dearmor |
    sudo tee /etc/apt/trusted.gpg.d/microsoft.gpg > /dev/null
- name: Install Azure CLI Software Repository
  shell: AZ_REPO=$(lsb_release -cs) && echo "deb [arch=amd64] https://packages.microsoft.com/repos/azure-cli/ $AZ_REPO main" |
    sudo tee /etc/apt/sources.list.d/azure-cli.list
- name: Install Azure CLI
  apt:
    name: azure-cli
    state: present
    update_cache: yes
