- name: Install Microsoft Package GPG Key
  shell: curl https://packages.microsoft.com/keys/microsoft.asc | gpg --dearmor > microsoft.gpg
- name: Move the GPG Key
  shell: sudo mv microsoft.gpg /etc/apt/trusted.gpg.d/microsoft.gpg
- name: Set up the APT source list before doing an APT update.
  shell: sudo sh -c 'echo "deb [arch=amd64] https://packages.microsoft.com/repos/microsoft-ubuntu-$(lsb_release -cs)-prod $(lsb_release -cs) main" > /etc/apt/sources.list.d/dotnetdev.list'
- name: Install Azure Functions Core Tools v3.x
  apt:
    name: azure-functions-core-tools-3
    state: present
    update_cache: yes
